#define MK_KINETIC_SPEED

// Cursor movement
#define MOUSEKEY_MOVE_DELTA            10
#define MOUSEKEY_INTERVAL               5
#define MOUSEKEY_DELAY                  0
#define MOUSEKEY_INITIAL_SPEED       3000
#define MOUSEKEY_BASE_SPEED         15000
#define MOUSEKEY_ACCELERATED_SPEED  25000
#define MOUSEKEY_DECELERATED_SPEED   400  // bem baixo para sniper mode

// Wheel movement
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS    8
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS       16
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 32
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 4
