#define EE_HANDS
// não defina MASTER_LEFT ou MASTER_RIGHT

#define MATRIX_SCAN_USER
#define PULLUP

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_DRIVER SIOD0
#define SERIAL_USART_TX_PIN GP20
#define SERIAL_USART_RX_PIN GP21
#define SERIAL_PIO_USE_PIO0    // Comunicação split via PIO0



#define JOYSTICK_BUTTON_COUNT 0
#define ANALOG_JOYSTICK_AXIS_MIN 0
#define ANALOG_JOYSTICK_SPEED_REGULATOR 16
#define JOYSTICK_AXIS_COUNT 2


#pragma once
