MCU = RP2040
BOOTLOADER = rp2040

DATA_DRIVER = yes

POINTING_DEVICE_DRIVER = analog_joystick
POINTING_DEVICE_JOYSTICK = yes
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog
ANALOG_DRIVER_REQUIRED = yes

SPLIT_KEYBOARD = yes
KEYBOARD_FILES += keyboards/handwired/dactyl_manuform/giacomeli_5x6/keyboard.json
CONSOLE_ENABLE = yes
DEBUG_MATRIX_SCAN_RATE = yes
